apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app : {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}
    spec:
      containers:
        - name : {{ .Release.Name }}-web
          image: {{ .Values.container.image}}
          imagePullPolicy: IfNotPresent
          env:
            - name: UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: AUTHOR
              value: {{ .Values.author.name }}
          ports:
            - containerPort: {{ .Values.container.port }}

          livenessProbe:
            httpGet:
              path: {{ .Values.endpoints.author }}
              port: {{ .Values.container.port }}
            initialDelaySeconds: {{ .Values.test_time }}
            periodSeconds: {{ .Values.test_time }}

          readinessProbe:
            httpGet:
              path: {{ .Values.endpoints.hostname }}
              port: {{ .Values.container.port }}
            initialDelaySeconds: {{ .Values.test_time }}
            periodSeconds: {{ .Values.test_time }}
