apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-service
  labels:
    owner: {{ .Values.author.name }}
spec:
  selector:
    project: {{ .Release.Name }}
  ports:
    - name      : {{ .Release.Name }}-listener
      protocol  : TCP
      port      : 8000
      targetPort: 8000