apiVersion: v1
kind: Namespace
metadata:
  name: cloudru
  labels:
    name: cloudru

---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: cloudru-test-task
  namespace: cloudru
  labels:
    app : cloudru-test-task-k8s-application
spec:
  replicas: 3
  selector:
    matchLabels:
      project: cloudru-test-task
  template:
    metadata:
      labels:
        project: cloudru-test-task
    spec:
      containers:
        - name : cloudru-test-task-web
          image: femakc/test_cloudru:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: server_host
              value: "0.0.0.0"
          ports:
            - containerPort: 8000

          livenessProbe:
            httpGet:
              path: /author
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 3

          readinessProbe:
            httpGet:
              path: /hostname
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 3

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: my-single-pod-service
#  labels:
#    owner: Max Fedorov
#spec:
#  selector:
#    project: cloudru-test-task
#  ports:
#    - name      : app-listener
#      protocol  : TCP
#      port      : 8000
#      targetPort: 8000
#  type: ClusterIP