apiVersion: v1
kind: Namespace
metadata:
  name: cloudru
  labels:
    name: cloudru

---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: cloudru-test-task
  namespace: cloudru
  labels:
    app : cloudru-test-task-k8s-application
spec:
  replicas: 3
  selector:
    matchLabels:
      project: cloudru-test-task
  template:
    metadata:
      labels:
        project: cloudru-test-task
    spec:
      containers:
        - name : cloudru-test-task-web
          image: femakc/test_cloudru:test1
          imagePullPolicy: IfNotPresent
          env:
            - name: UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          ports:
            - containerPort: 8000

          livenessProbe:
            httpGet:
              path: /author
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /hostname
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  namespace: cloudru
  name: my-single-pod-service
  labels:
    owner: Max
spec:
  selector:
    project: cloudru-test-task
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 8000
      targetPort: 8000
#  type: ClusterIP